version: '3.7'
services:

    postgres_ecommerce-manager-service:
        image: postgres:13
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=ecommercemanager
          
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./ecommerce-manager-service/src/main/resources/ecommerce_carvajal.sql:/docker-entrypoint-initdb.d/ecommerce_carvajal.sql
          
    ecommerce-manager-service:
        container_name: ecommerce-manager-service
        build:
          context: ./ecommerce-manager-service
        depends_on:
            - postgres_ecommerce-manager-service
        deploy:
          replicas: 1
          resources:
            limits:
              cpus: 0.22
              memory: 256M
            reservations:
              cpus: 0.12
              memory: 128M
        ports:
          - 9000:9000